### ISSUE TITLE
null / undefined should display as blank

### ISSUE THREAD

**Issue by matthampton-stock2shop** [stock2shop/console_v2#108]
Is there a general purpose way to handle this in svelte (e.g. React doesn't render anything for null/undefined)...

e.g. in this screen:

![image](https://user-images.githubusercontent.com/124143173/234561978-7a982109-ff18-4d56-b12f-bb040414671d.png)

**Comment by TomRadford** [comment]
Solution is to render these optional properties with a conditional (`#if`) blocks. 
Have been employing this strategy to prevent undefined / null leaks into the UI as I work through the codebase.
@matthampton-stock2shop happy to close this?

**Comment by matthampton-stock2shop** [comment]
> Solution is to render these optional properties with a conditional (`#if`) blocks. Have been employing this strategy to prevent undefined / null leaks into the UI as I work through the codebase. @matthampton-stock2shop happy to close this?

Sure... happy
