### ISSUE TITLE
Bug: When editing a product the source_variant_code is populated into the product code field

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#175]
The `source_product_code` for the product in the screengrab is "ZOMBIE-LB"

![image](https://github.com/stock2shop/console_v2/assets/2038721/fa52c33a-3c9d-4c39-b0a6-5279fc59edc9)

**Comment by justinengle-krs** [comment]
@mannyqi I think maybe the label is wrong? As per the old console it should be the variant code, see below.

![image](https://github.com/stock2shop/console_v2/assets/125956275/efbaeaad-3dc8-4409-9d25-06ccb6d89390)

You can also see in the design the product code on the actual product is different to the variant
https://app.zeplin.io/project/629fb41be1a2021104a7cae0/screen/63bc48d2123fb391f05b92ae

Unless this was an intended change i think maybe the label is just incorrect?

**Comment by mannyqi** [comment]
> I think maybe the label is wrong? As per the old console it should be the variant code

@justinengle-krs I think you're right. Also note the product code is already displayed to the right of the image in the new console.

**Comment by justinengle-krs** [comment]
> > I think maybe the label is wrong? As per the old console it should be the variant code
> 
> @justinengle-krs I think you're right. Also note the product code is already displayed to the right of the image in the new console.

Should I change the label perhaps? To Source Variant code?

**Comment by mannyqi** [comment]
> Should I change the label perhaps? To Source Variant code?

Sorry, please do. I think it should just be "Variant Code".
