### ISSUE TITLE
Products grid - Include a "Show Variants" toggle

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#203]
We need to include a "Show Variants" toggle as per design. 
When active, each product will show its variants below the product.

![image](https://github.com/stock2shop/console_v2/assets/2038721/90c018a8-921f-484c-8ba2-eb9d4d400c6f)

#### Old console
![image](https://github.com/stock2shop/console_v2/assets/2038721/49571301-da19-48a9-8d43-3b0a20cca521)

**Comment by matthampton-stock2shop** [comment]
@justinengle-krs That's a good point... I will go and see if I can find the design (if there was one)

**Comment by TomRadford** [comment]
Implemented in https://github.com/stock2shop/console_v2/pull/270
