### ISSUE TITLE
Bug: product channels tab errors with undefined channel_variant_code

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#207]
When viewing a product's "Channels" tab I see the following in my browsers developer console:

<img width="1714" alt="error" src="https://github.com/stock2shop/console_v2/assets/2038721/6c766a28-8995-476e-aed2-208f6ac6c1f2">

### Steps to Reproduce:
1. Create a new channel (e.g. WooCommerce) in the admin system
2. Login to the client and activate the newly created channel

<img width="1688" alt="3" src="https://github.com/stock2shop/console_v2/assets/2038721/6bed8c73-db88-447a-b22d-bb64716be9fa">

3. View any product's channel tab with the browsers developer console open

--- 

When loading the product view's channel tab, the GET variants/5313457/channels?token=XXXXXXXX endpoint will return a response like this one:

```json
{
    "system_variant_channels": [
        {
            "id": 8973631,
            "created": "2023-02-24 13:56:16.000000",
            "channel_variant_code": "5313457",
            "variant_id": 5313457,
            "modified": "2023-05-17 09:48:13.000000",
            "channel_id": 47,
            "active": 1,
            "client_id": "21"
        },
        {
            "id": 8973633,
            "created": "2023-02-24 13:56:17.000000",
            "channel_variant_code": "5313457",
            "variant_id": 5313457,
            "modified": "2023-02-27 12:09:18.000000",
            "channel_id": 1881,
            "active": 1,
            "client_id": "21"
        },
        {
            "id": 10387918,
            "created": "2023-05-17 09:48:01.000000",
            "channel_variant_code": "39851748163642",
            "variant_id": 5313457,
            "modified": "2023-05-17 09:48:15.000000",
            "channel_id": 197,
            "active": 1,
            "client_id": "21"
        }
    ]
}
```

**Comment by mannyqi** [comment]
@justinengle-krs 

The problem is happening in [this](https://github.com/stock2shop/console_v2/blob/a6a8a59f8125d64a7e30e13ecb8e1fb159e8668c/src/components/Product/ProductChannels.svelte#L84C13-L84C13) function. 

You fetch the [channels for a variant](https://github.com/stock2shop/console_v2/blob/a6a8a59f8125d64a7e30e13ecb8e1fb159e8668c/src/components/Product/ProductChannels.svelte#L85). 
Then [find the channel](https://github.com/stock2shop/console_v2/blob/a6a8a59f8125d64a7e30e13ecb8e1fb159e8668c/src/components/Product/ProductChannels.svelte#L86) from those results which matches the channel being passed into the function. 
No match will be found in the case where no variant/s has been assigned to the new channel. So `variantChannel` will be "undefined".

**Comment by justinengle-krs** [comment]
Thanks for the input @mannyqi !
