### ISSUE TITLE
When trying to "manage a template", all of the types are greyed out for existing template attributes

### ISSUE THREAD

**Issue by matthampton-stock2shop** [stock2shop/console_v2#208]
When trying to manage a template, all of the types are greyed out for existing template attributes:

![image](https://github.com/stock2shop/console_v2/assets/124143173/3e1a12fd-486f-4237-a6bb-2e0cc5615503)

If I add a new one I can choose the type.

_Originally posted by @matthampton-stock2shop in https://github.com/stock2shop/console_v2/pull/197#discussion_r1285755878_

**Comment by justinengle-krs** [comment]
As discussed with @matthampton-stock2shop 
The API does not allow editing of these values, so this is intended behaviour, but lets make sure the dropdown displays the value even if its disabled
