### ISSUE TITLE
Segments - Show Data Source

### ISSUE THREAD

**Issue by justinengle-krs** [stock2shop/console_v2#212]
![image](https://github.com/stock2shop/console_v2/assets/125956275/0e34fffb-878c-4250-99ad-4eefa1c12145)

**Comment by TomRadford** [comment]
@matthampton-stock2shop Keen to chat about the data source and functionality for this drop down.

**Comment by TomRadford** [comment]
Functionality notes from chat with Matt:

- Data source mapped from `segment.owner`
- This page is most valuable from a viewing perspective for Source segments
- Data sources should only be mutable if they're set on S2S (owner === `system`)
