### ISSUE TITLE
Bug bucket

### ISSUE THREAD

**Issue by casperlotter** [stock2shop/console_v2#216]
Using this issue to track anything found in testing to ensure we coordinate and not create additional noise before spinning out valid issues.

**Comment by casperlotter** [comment]
Product and customer search Icon:

![Screenshot 2023-08-14 154707](https://github.com/stock2shop/console_v2/assets/129734011/a369b74b-7c10-490a-9aaa-f56493dc143e)

**Comment by casperlotter** [comment]
FacetManager strange behaviour when opening or closing sometimes. 

Underlying text being dragged clicked. 

![Screenshot 2023-08-14 161330](https://github.com/stock2shop/console_v2/assets/129734011/d5f4cfab-2a19-4601-b84e-6aafb8436c9b)

**Comment by casperlotter** [comment]
Customer segment controls and other not opening modal subsequently:

![Screenshot 2023-08-14 161622](https://github.com/stock2shop/console_v2/assets/129734011/254aed7b-2d1b-4d74-aeea-0da1b2edf9b0)

**Comment by tauriqdolleyKRS** [comment]
Bottom of page is cut off.

![image](https://github.com/stock2shop/console_v2/assets/142212593/ff239a5a-b061-43b8-876c-fe024b9fcce0)

**Comment by tauriqdolleyKRS** [comment]
No validation on min and max, also doesn't seem to filter correctly

![image](https://github.com/stock2shop/console_v2/assets/142212593/ea832426-f82a-4f62-a839-e298e44796e8)

**Comment by tauriqdolleyKRS** [comment]
Cut off Filters Modal 

![image](https://github.com/stock2shop/console_v2/assets/142212593/05a1c6fa-bf13-4631-8519-a25020b24b93)

**Comment by tauriqdolleyKRS** [comment]
Type Error when uploading CSV for product import 
![image](https://github.com/stock2shop/console_v2/assets/142212593/a3d0afaf-21d0-4b58-a1c4-50da5670257c)

Also when using matching columns it loads generic data for each row imported
![image](https://github.com/stock2shop/console_v2/assets/142212593/eecb9ea1-9bd5-4b07-a74e-3a5426213246)

**Comment by tauriqdolleyKRS** [comment]
Remove Margin-Top from Dashboard Header - doesn't vertically align

![image](https://github.com/stock2shop/console_v2/assets/142212593/a859cb4f-8525-4838-9722-e83a158a9ad2)

**Comment by tauriqdolleyKRS** [comment]
Add User button refetches but no functionality or console.log()

![image](https://github.com/stock2shop/console_v2/assets/142212593/ef79561b-6a79-494d-b998-a12647f7a64d)

**Comment by tauriqdolleyKRS** [comment]
Settings / Product Templates 

Scroll Overflow Issue
![image](https://github.com/stock2shop/console_v2/assets/142212593/3a862f1e-9f59-45b5-87a7-1ab44017dd73)

Attribute count defaults to 5 regardless of actual count
![image](https://github.com/stock2shop/console_v2/assets/142212593/0c600cf5-6221-4fb9-b7ec-35d7bd513a54)

**Comment by justinengle-krs** [comment]
![image](https://github.com/stock2shop/console_v2/assets/125956275/b10b4a5e-7b18-48cc-9d96-17571b693fd2)

**Comment by justinengle-krs** [comment]
![image](https://github.com/stock2shop/console_v2/assets/125956275/66e97c92-1120-4733-aed2-0a9fbe65fa35)

**Comment by tauriqdolleyKRS** [comment]
Dynamic Pricing Columns - Bad Alignment

![image](https://github.com/stock2shop/console_v2/assets/142212593/3f90b84e-9a3c-44ec-8c71-e6f448f30d0b)

**Comment by tauriqdolleyKRS** [comment]
> Dynamic Pricing Columns - Bad Alignment
> 
> ![image](https://user-images.githubusercontent.com/142212593/263993945-3f90b84e-9a3c-44ec-8c71-e6f448f30d0b.png)

https://github.com/stock2shop/console_v2/pull/261
