### ISSUE TITLE
Add Combobox in appropriate places

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#217]
Currently when adding a segment a dropdown with a list of the base fields is used.

![image](https://github.com/stock2shop/console_v2/assets/2038721/c72a47fd-7125-4256-915c-82b1cbe740b5)

This dropdown should eventually be replaced with the lookahead feature from [this PR](https://github.com/stock2shop/app/pull/2019)

**Comment by TomRadford** [comment]
We should be able to use a variation of FieldSelector here (which uses the new `fields` endpoint) to speed this one up.

**Comment by TomRadford** [comment]
This one branches off of work done in #360 by implementing it in appropriate places (see above)

**Comment by TomRadford** [comment]
note that there are additional places this needs to be added but I want to merge the work done since I'm going on leave and the PR for this ticket introduces some essential fixes to `FieldSelector` and `ComboBox`
