### ISSUE TITLE
Info display does not transition back to a gray button once you have saved:

### ISSUE THREAD

**Issue by casperlotter** [stock2shop/console_v2#244]
Info display does not transition back to a gray button once you have saved:

![Screenshot 2023-08-14 162729](https://github.com/stock2shop/console_v2/assets/129734011/10e82067-30b7-4d38-a0bd-fb1735f9b121)

_Originally posted by @casperlotter in https://github.com/stock2shop/console_v2/issues/216#issuecomment-1677426287_

**Comment by TomRadford** [comment]
Got a bugfix ready just waiting for @justinengle-krs's feedback on https://github.com/stock2shop/console_v2/commit/1ec1c8d69c99d45f122c377dbe4f109d305930c2#r126690552 and https://github.com/stock2shop/console_v2/commit/f31e21231b0c522880586afbc65d90dc0edb0994#r126696527
