### ISSUE TITLE
Style Product Edit Page

### ISSUE THREAD

**Issue by flumonion** [stock2shop/console_v2#26]
@vonsyus 
Create Styles for product edit page, see below.
Don't worry about any of the functionality, just style the page.

![Screenshot 2022-08-25 at 08 31 35](https://user-images.githubusercontent.com/1546805/186595823-828be1b5-2f1b-4ce9-9500-4744bdde1225.png)

A product can have one or many variants.
The variant fields is on the right hand side of the page, the product fields are on the left hand side.
If it only has one variant, then there are no "options" for the product the below checkbox is not active.

NB: The below picture is actually wrong, the options box would be hidden if "This product has different options" is not checked...

![Screenshot 2022-08-25 at 08 56 55](https://user-images.githubusercontent.com/1546805/186596261-b3529b88-b019-4b0f-ae91-6ca9bf016fb5.png)

Let's focus on a product without options to start.

A variant can have multiple "price lists" and "warehouses".
The warehouse picture is also wrong, the warehouse value should be a number, not a string.
It is the quantity of the variant in the warehouse.

![Screenshot 2022-08-25 at 08 54 00](https://user-images.githubusercontent.com/1546805/186595865-aaef3aa1-c510-41bf-848a-59ce44570a54.png)
![Screenshot 2022-08-25 at 08 54 17](https://user-images.githubusercontent.com/1546805/186595886-ec54f53c-d5b6-458f-b063-bbb34a7fe4dc.png)

**Comment by TomRadford** [comment]
This has been implemented
