### ISSUE TITLE
esStore Refactor

### ISSUE THREAD

**Issue by flumonion** [stock2shop/console_v2#29]
Taken from Keybase message from @AndrewKirkovski 

What I'm trying to do:
1. Get rid of direct access to store structure, especially `$esStore[index]`. Incapsulating that in methods allows to change internal logic as we please in one place, instead of touching all components when some naming or concept changes. Also that separates "calculation logic" and "controller/presentation" 
2. Get rid of direct dependency on svelte query inside of es lib
3. Allow to have on-demand separate stores, instead of big one with everything. This allows nicer use of derived substores like observables for all main stuff like facets and requests

How:
1. Instead of module with exported constant we will have a hook, that will handle all store creating on its own 
Before:
```ts
if (!$esStore[index]) {
    init(
      index,
      { path: esRoutes.searchProducts },
      undefined,
      $productFacets,
    );
    if (params.search) {
      setSearch(index, params.search, $configPersistent.elasticSearch.products.searchFields);
    }
    prepareRequest(index);
  }
```
After:
```ts
const {
    facets,
    request,
    store,
    setSearch,
    isDataInvalidated,
    submitChanges,
    data: result,
  } = useElasticSearchContext<SystemProductsResponse>(index, {
    request: { path: esRoutes.searchProducts },
    facets: productFacets,
  }, (context) => {
    if (params.search) {
      context.setSearch(params.search, $configPersistent.elasticSearch.products.searchFields);
    }
  }, () => {
    queryClient.invalidateQueries(index);
  });
```

As you can notice, this exports methods like 'setSearch' that do not require specifying index, so we can have much cleaner looking method for setting new search query for example:
Before:
```ts
      setSearch(index, q);
      prepareRequest(index);
      queryClient.invalidateQueries(index);
```
After:
```ts
      setSearch(q);
      submitChanges();
```

Note we no longer need to call query invalidate, query invalidation is done automatically in a useElasticSearchContext

We also get rid of reactive accessors
Before
```ts
let request: APIRequest<DSL>; // hack for IDE to understand type

  $: request = getStoreEntryRequest($esStore, index);

  const data = useIndexQuery(index, () => postElasticSearch<SystemProductsResponse>(request.path, request.body, request.params));

  let result: SystemProductsResponse;
  $: result = getStoreEntryData<SystemProductsResponse>($esStore, index);

  $: facets = getStoreEntryFacets($esStore, index);
```
After
```ts
   const data = useIndexQuery(index, () => postElasticSearch<SystemProductsResponse>($request.path, $request.body, $request.params));
   $: isLoading = $data.isLoading && $isDataInvalidated;
    $: isFetching = $data.isFetching && $isDataInvalidated;
```

facets and data are "premade" as observables and can be used directly
Draft of this concept (non-working code) is located in [feature/experiment](https://github.com/stock2shop/console_v2/blob/feature/experiment/src/lib/es/useElasticSearchContext.ts)
Internals of es components will also get simplified a lot
I.e. Search.svelte
Before
```ts
const queryClient = useQueryClient();

  // Search aggregations and update results
  const doSearch = () => {
    $esStore[index].search_fields = search_fields;
    $esStore[index].sort = {
      _score: {
        order: 'desc'
      }
    };
    setFrom(index, 0);
    setSearch(index, $esStore[index].search, search_fields);
    prepareRequest(index);
    queryClient.invalidateQueries(index);
  };
```
After
```ts
const { setSearch, submitChanges, store } = getElasticSearchContext(index);

  // Search aggregations and update results
  const doSearch = () => {
    setSearch(search, search_fields);
    submitChanges();
  };

```
This also still preserves an idea of having all of that stuff cross accessible globally, but would require to be bit more explicit about where exactly

**Comment by TomRadford** [comment]
This works well, closing. (note when we move to TanStack Query v5 some changes will be needed as per https://github.com/stock2shop/console_v2/commit/24e8369b0af65260a5f757458db50c832d7f12e4)
