### ISSUE TITLE
Dates need to be displayed in their timezone

### ISSUE THREAD

**Issue by TomRadford** [stock2shop/console_v2#361]
Tasks:
- Scanning through pages where we render dates and times 
- Checking that we're rendering them in consistent format
- Checking that we're rendering them in the user's timezone consistently 
- Make sure all the dev docker containers are === UTC + 0

Implementation:
- Parsing UTC times into local. 

Concern: 
- Our Ubuntu server is set in UTC (in prod?). 
- Matt tried his darndest to make sure all dev docker container's local time === UTC + 0

Goal:
- We want to parse into the browser's local time 🕰️

**Comment by TomRadford** [comment]
Tasks:
- Scanning through pages where we render dates and times 
- Checking that we're rendering them in consistent format
- Checking that we're rendering them in the user's timezone consistently 
- Make sure all the dev docker containers are === UTC + 0

Implementation:
- Parsing UTC times into local. 

Concern: 
- Our Ubuntu server is set in UTC (in prod?). 
- Matt tried his darndest to make sure all dev docker container's local time === UTC + 0

Goal:
- We want to parse into the browser's local time 🕰️

**Comment by martins2s** [comment]
# Notes

### Date function on Console v2 UI

|format/function|display|local|usages|notes
|---|---|---|---|---|
|formatDate|2024-03-11, 08:30:51|Buggy|OrderHistory, OrderHistoryModal, ProductChannels, ProductDataSyncLogs, ProductSyncSourceModal
|dateWithOridinalDay|5th March 2024|Yes|ProductDetails|
|getLocalShortDay + getLocalShortTime|Tue 5:32PM|Yes|Alerts, DashboardSyncPush, DashboardSyncPull, LogTable|
|getLocalDate|2024-03-12 13:15:46|Currently no|QueueErrorTableDateCell|Correctly parses string date at UTC, but then uses .toISOString, which isn't local
|None|2024-03-12 13:15:46 (dependent on api format)|No|Attribute, DataSync, 
|Custom |Mon Mar 11 2024 06:30:51|Buggy|CustomerSummary

### Date fields in db
- created
- modified
- created_at
- updated_at
- dated_on
- due_on
- next_schedule
- synced
- channel_synced
- token
- row_modified
- otp_generated
- ordered_date
- start_date
- end_date
- expiration_date

### Need to think about

- Date filters on UI 
    - Date picker display (not sure if we're in control of format)
    - should they be converted to UTC first before sending the API?
