### ISSUE TITLE
Stub out / complete ordering functions on the list page

### ISSUE THREAD

**Issue by matthampton-stock2shop** [stock2shop/console_v2#383]
Whichever is easier

**Comment by matthampton-stock2shop** [comment]
> @matthampton-stock2shop just checking what functionality you're referring to here?
> 
> 1. is there meant to be a complete button on order list page?
> 2. or are you referring the create order button on the Order Page:
>   

Sorry! That was very vague... I was talking about these:

<img width="474" alt="image" src="https://github.com/stock2shop/console_v2/assets/124143173/f0348a59-7d19-4ac3-85f2-9474fe41729a">

up and down arrows to order things on the product (and other?) list page

I think we only let you do it for created / modified time - which doesn't feel that useful...

But..... Doing an ordering when there is any full text search going on breaks the elastic search match scoring algorithm

.e.g if this search had more results - we'd want to let them be ordered by how good the search match is:

<img width="427" alt="image" src="https://github.com/stock2shop/console_v2/assets/124143173/bcf8e47d-3272-4a9c-9564-540118ffb61d">

**Comment by matthampton-stock2shop** [comment]
So I think what we decided was that - if we are even going to do this:

1. You should not be able to order if there is a search term
2. But you should be able to if it is a filter (e.g.
    
    <img width="300" alt="image" src="https://github.com/stock2shop/console_v2/assets/124143173/1c08809e-de09-4ef2-9dd3-d03326bf883b">

And you should really be able to order on any of the columns, if we support this at all

**Comment by matthampton-stock2shop** [comment]
I'm not sure how hard that will be, though - i.e. is it easy to adjust our elastic search query to include an ordering on any column (it might be?)

But if not, then I think we can just take out the feature to order by created / modified date - which seems half-baked

**Comment by TomRadford** [comment]
Discussed: 
Just remove the sort button for now - could turn into something quite complex. 
STUB OUT

**Comment by TomRadford** [comment]
Leave as is
