### ISSUE TITLE
[Channel Settings] Bugs: Info Display

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#398]
# ACCOUNT DISPLAY, PRODUCT INFO DISPLAY
System allows adding of empty key, value pairs

### Steps to reproduce:
1. Add a field and enter any key and value (don't save)
2. Add another field and leave blank
3. Click save

<img width="1024" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/8a9ecc07-ef06-42ca-96b0-9167fb97d818">

#### Expected result:
System prevents you from saving the account display settings if there are empty key, value pairs.

#### Actual result:
System allows you to add empty key, value pairs after including on pair with data.

---

#

**Comment by TomRadford** [comment]
@mannyqi would you mind uploading this screenshot again?

**Comment by mannyqi** [comment]
Sorry about that
