### ISSUE TITLE
[Product] Bugs: Channels

### ISSUE THREAD

**Issue by mannyqi** [stock2shop/console_v2#429]
# 1. Testing with Demo Data

## Channels
Saving and deletion does not work.
Trying to delete any of the channel sku lines does not do anything.
Also, making any kind of changes does not activate the "Save Changes" button.

# 2. Testing with Client Data
### Channels
Channels tab fails to load for some products with following error in console:

![image](https://github.com/stock2shop/console_v2/assets/2038721/631bce8f-19b2-49a5-9839-3cb704dafde2)

**Comment by TomRadford** [comment]
Chatted to Matt and we've opted to stub out editing functionality and add backlink in separate ticket https://github.com/stock2shop/console_v2/issues/472

**Comment by TomRadford** [comment]
We discussed how we can clean this up quite a bit by introducing a new endpoint... however, that will take time and effort. It works nicely in the current PR (albeit lots of complexity)  https://github.com/stock2shop/console_v2/pull/473 so we opted to get this tested (@Ayano2000 to test) and merge - so at least the feature is implemented and works for launch 🥇
