### ISSUE TITLE
Mobile / Responsive design expectations

### ISSUE THREAD

**Issue by justinengle-krs** [stock2shop/console_v2#62]
@matthampton-stock2shop 

Please confirm what the expectations are regarding mobile design.

Also, when doing desktop are we going for pixel perfect match to Zeplin regarding padding etc ? i.e 24px in Zeplin/Figma is 24px in browser

**Comment by matthampton-stock2shop** [comment]
> Please confirm what the expectations are regarding mobile design.

This is a desktop UI. ie Responsiveness is only relevant across different desktop screen sizes - we are not targeting mobile screens.

> Also, when doing desktop are we going for pixel perfect match to Zeplin regarding padding etc ? i.e 24px in Zeplin/Figma is 24px in browser

We'd like to aim for this - but please raise a flag if something is proving particularly tricky / costly to get pixel perfect. Have you seen the developer tools in Zeplin? (I have not seen them - but understand that it should give you some useful things to work with)

@flumonion Please chip in here if you have a different opinion

**Comment by justinengle-krs** [comment]
Okay. Thank you and noted. I have had a look, the Zeplin tools are very helpful. There are just some odd cases I've come across in the past where it can be a tricky to be 100% pixel perfect along with the responsive design. But we shall raise this IF something like that ever crops up.

**Comment by matthampton-stock2shop** [comment]
> Okay. Thank you and noted. I have had a look, the Zeplin tools are very helpful. There are just some odd cases I've come across in the past where it can be a tricky to be 100% pixel perfect along with the responsive design. But we shall raise this IF something like that ever crops up.

Yeah - makes sense - and we don't want to burn up time on edge cases - so please do raise a flag if you run in to something like that and we can discuss it
