### ISSUE TITLE
When trying to retrieve a non existent customer - 403 Status Returned

### ISSUE THREAD

**Issue by justinengle-krs** [stock2shop/console_v2#63]
If I try and get a customer by ID via the following endpoint

https://app.stock2shop.com/v1/customers/{customerId}

and no customer with that ID exists then the API returns a 403 Forbidden which does not seem correct. This means that the frontend can't easily distinguish between being unauthorized or the resource not existing

**Comment by mozey** [comment]
Assume the token used below is valid for `client_id=21`
```
curlie "https://app.stock2shop.com/v1/customers/1?token=xxx"
HTTP/1.1 403 Forbidden

curlie "https://app.stock2shop.com/v1/customers/10000000?token=xxx"
HTTP/1.1 404 Not Found
```

- [403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) is returned if you request a *customer_id* that belongs to a *client_id* that differs from your *token*

- `404 Not Found` is returned if the *customer_id* doesn't exist on Stock@Shop

**Comment by mozey** [comment]
Also consider the following response
```
curlie "https://app.stock2shop.com/v1/customers/10000000?token=invalid"
HTTP/1.1 401 Unauthorized
```

- [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) is returned if you use an invalid token

**Comment by justinengle-krs** [comment]
Noted! Thanks for the feedback.
