### ISSUE TITLE
License for icons

### ISSUE THREAD

**Issue by matthampton-stock2shop** [stock2shop/console_v2#71]
@flumonion @mannyqi  Are all of the icons from https://heroicons.com/? (Just wondering if we need to be concerned about licenses etc. - looks like that library is MIT licensed - so quite permissive - but I do think we should keep a record of where these are from and maybe a copy / link to the license in a readme.

_Originally posted by @matthampton-stock2shop in https://github.com/stock2shop/console_v2/pull/50#discussion_r1122904474_

**Comment by TomRadford** [comment]
@flumonion did the designer ever come back to us on this?

**Comment by matthampton-stock2shop** [comment]
> @flumonion did the designer ever come back to us on this?

He did - he said that he either made them or is licensed to share them with us but didn't give details

**Comment by TomRadford** [comment]
@matthampton-stock2shop happy to close this without license details?
