### ISSUE TITLE
Handling Dirty data and updates with svelte-query

### ISSUE THREAD

**Issue by justinengle-krs** [stock2shop/console_v2#72]
It was concluded that we don't want to work with stale data, and if the data updates while a user is editing, then we need to notify them.
Also, we need to track if any change has been made.

To achieve this we need 3 copies of the object:

- Original - this is the first version of the object we fetched
- Working Copy - this is the version that binds to the frontend that the user can edit
- Updated/Fresh - this version is kept fresh with the Svelte-query library

This would be quite a challenge to maintain as 1 prop becomes 3.... 3 props become 9....etc...
I propose some kind of Generic Version controlled object (Open to a better name).

Create a generic version controlled type object
```
export default class ObjectVersionControl<T extends Modifiable> {
  original: T;
  workingCopy: T;
  updatedVersion: T;

  constructor(original: T) {
    this.original = original;
    this.workingCopy = { ...original };
    this.updatedVersion = { ...original };
  }

  update(updatedVersion: T) {
    this.updatedVersion = updatedVersion;
  }
  
  get changesMade() {
    return JSON.stringify(this.original) !== JSON.stringify(this.workingCopy);
  }

  get isStale() {
    return this.updatedVersion.modified !== this.workingCopy.modified;
  }
}
```

Usage on a svelte component:

Define

`let customerVersionControlled: ObjectVersionControl<SystemCustomer>;`

Update accordingly with `useQuery`

```
 const customerData = useQuery(['customer-get', customerId], () => getCustomerById(customerId),{
    onSuccess(data) {
      const systemCustomerUser = new SystemCustomer(data);
      if (!customerVersionControlled) customerVersionControlled = new ObjectVersionControl<SystemCustomer>(systemCustomerUser);
      else customerVersionControlled.update(systemCustomerUser);
    },
  });
```

Bind to workingObject

`<input bind:value={customerVersionControlled.workingCopy.first_name}` />

on Save:

```
if(customerVersionControlled.changesMade){
      // prompt save
    }
    
if(customerVersionControlled.isStale){
    //prompt override or cancel
    }    
```

@matthampton-stock2shop  I think this could be a nice implementation, keeps this logic self contained, curious to hear your thoughts.

**Comment by matthampton-stock2shop** [comment]
I like this, @justinengle-krs ... looks good

**Comment by matthampton-stock2shop** [comment]
And guessing that in here:

```
update(updatedVersion: T) {
    this.updatedVersion = updatedVersion;
  }
```
You can update original + working copy if it is stale but has not got any changes ?

**Comment by flumonion** [comment]
> All our editable models have an modified property with a time stamp, to ensure we can rely on this and make it strongly typed lets introduce an interface

Just a bit worried that some models timestamps are not reliable.
For example, if a price list is changed on a product, does its timestamp for the product change?

We would need to confirm this, feels it might be a bit risky and to fix the issue if there was one, we would need to start changing API code...

**Comment by justinengle-krs** [comment]
> > All our editable models have an modified property with a time stamp, to ensure we can rely on this and make it strongly typed lets introduce an interface
> 
> Just a bit worried that some models timestamps are not reliable. For example, if a price list is changed on a product, does its timestamp for the product change?
> 
> We would need to confirm this, feels it might be a bit risky and to fix the issue if there was one, we would need to start changing API code...

We could perhaps do an entire object comparison like the `changesMade` perhaps then instead

**Comment by flumonion** [comment]
> We could perhaps do an entire object comparison like the changesMade then instead

You could hash everything and compare hashes, but that gets complicated fast.

Perhaps, to throw spanner in the works here...
Another approach could be to turn off automatic refresh on queries for editable screens.
When the editable item is saved we re-query to check if anything is changed and display appropriate prompt before saving?
This could use a hash function for this? Or if you need to know what field changed, then something else...

Means you don't have to worry about versioning etc and makes ui code simpler.

It is nice to have the screen auto update, but it is challenging to handle from a ui perspective and potentially adds additional unnecessary requests to the server?

**Comment by matthampton-stock2shop** [comment]
I'd vote for "an entire object comparison like the changesMade then instead"...

It's simple to implement and it doesn't matter making someone's browser do a bit of work

**Comment by TomRadford** [comment]
our custom `VersionControlledStore` is working well.
