### ISSUE TITLE
Page Fluid vs Fixed

### ISSUE THREAD

**Issue by flumonion** [stock2shop/console_v2#75]
There are certain pages where the design is fluid and others where it is fixed width.
Currently, all pages are set to fixed width.

For example, `/products` should be fluid but `/channel/{id}` should be fixed.

<img width="1633" alt="Screenshot 2023-03-06 at 08 26 21" src="https://user-images.githubusercontent.com/1546805/223034782-010012ad-e87b-4641-8ed8-dba400cfadf5.png">
<img width="1634" alt="Screenshot 2023-03-06 at 08 26 32" src="https://user-images.githubusercontent.com/1546805/223034785-dc9def0b-19a2-4677-9da9-8a838ce53f7e.png">

**Comment by TomRadford** [comment]
Resolved in current console
