### ISSUE TITLE
Handle Invalid Session

### ISSUE THREAD

**Issue by flumonion** [stock2shop/console_v2#76]
If you load the application and you have an invalid token stored in browser cache, the application errors. It is not obvious to the user they need to log in again.

We need to figure out a nice workflow for this.

On our current console, the user is automatically logged out when an "unauthorised" response is received from API.
This could be an option?

**Comment by justinengle-krs** [comment]
Yes, I think the simplest and more secure option would be if unauthorized is received then we go to login screen. Instead of storing creds and re authing

**Comment by justinengle-krs** [comment]
https://trello.com/c/6UhprLh3/31-handle-invalid-session
